"""create users table

Revision ID: 24f2a380b7e8
Revises: 
Create Date: 2026-02-17 19:42:21.931300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2a380b7e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_image', type_='foreignkey')
    op.drop_column('hotel_image', 'city_id')
    op.alter_column('users', 'user_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'user_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('hotel_image', sa.Column('city_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'hotel_image', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###
